services:
  - type: web
    name: fswd-todolist
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lessons
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
